apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: aceapplications.ibm-ace-drayner.me
spec:
  group: ibm-ace-drayner.me
  names:
    kind: AceApplication
    listKind: AceApplicationList
    plural: aceapplications
    singular: aceapplication
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AceApplication is the Schema for the aceapplications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AceApplicationSpec defines the desired state of AceApplication
          properties:
            aceBaseImage:
              type: string
            aceImageTag:
              type: string
            aceKeystorePwd:
              type: string
            aceServerName:
              type: string
            aceTruststorePwd:
              type: string
            barLocation:
              type: string
            cpuLimit:
              type: string
            cpuRequest:
              type: string
            enableMetrics:
              type: string
            keystore:
              type: string
            license:
              type: string
            logFormat:
              type: string
            memoryLimit:
              type: string
            memoryRequest:
              type: string
            policy:
              type: string
            serverConfig:
              type: string
            setDBParms:
              type: string
            truststore:
              type: string
            webusers:
              type: string
          required:
          - aceBaseImage
          - aceImageTag
          - aceKeystorePwd
          - aceServerName
          - aceTruststorePwd
          - barLocation
          - cpuLimit
          - cpuRequest
          - enableMetrics
          - keystore
          - license
          - logFormat
          - memoryLimit
          - memoryRequest
          - policy
          - serverConfig
          - setDBParms
          - truststore
          - webusers
          type: object
        status:
          description: AceApplicationStatus defines the observed state of AceApplication
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
